version: '3'

services:
  nessus:
    container_name: nessus-7.2.3
    build:
      context: .
      dockerfile: Dockerfile_nessus
    restart: always
    ports:
     - "8834:8834"
    networks:
     - nessusnet
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elk:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    restart: always
    networks:
      - stack_zabbix
volumes:
  elk:
    driver: local
networks:
  nessusnet:
  
